apiVersion: v1
kind: Service
metadata:
  name: mlops-sample-project
  namespace: mlops-sample-project
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: mlops-sample-project
