name: Retrain Model

on:
  schedule:
    - cron: '0 0 * * *' # Retrain every day at midnight (UTC)

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install Dependencies
      run: |
        pip install -r app/requirements.txt

    - name: Fetch Latest Data
      run: |
        python data/fetch_data.py

    - name: Retrain Model
      run: |
        python model/train.py
